### ISSUE TITLE
SAML SSO for Chrome Apps not working with Chrome Update 72.0.3626.97 from 71

### ISSUE THREAD

**Issue by nlochrie** [GoogleChrome/chromeos_saml_apps#1] opened 2019-02-20 17:16 UTC
We are experiencing issue with the SAML SSO for Chrome Apps extension on Chrome starting this week with version 72.0.36.26.97.  
The previous version of 71 was working fine.  

Can you confirm that its working ok?

We are using it with chromeboxes, chromebooks(pixelbook).

Any help greatly appreciated.

**Comment by jay0lee** [comment] 2019-02-21 20:47
- Can you update to 72.03626.117 and test again? Note that that version won't be released for pixelbook for a few days but may be available on your chromebox).
- If the newer 72 version doesn't fix this for you can you try going to chrome://flags#network-service and toggling it off? Does it work with the network service off? Does it work if you set network service to on? (you need to restart Chrome OS after each change).

**Comment by nlochrie** [comment] 2019-02-22 00:57
Thanks for the reply.

Will do, we will test 72.03626.117 when it comes out for the pixelbook.  We
will also try an HP Chromebook, and ChromeBox.

Is there way to turn logging on for SAML SSO for Chrome Apps?  and where
would the log be on a chromebox/chromebook?

Thanks


On Thu, Feb 21, 2019 at 12:47 PM Jay Lee <notifications@github.com> wrote:

>
>    - Can you update to 72.03626.117 and test again? Note that that
>    version won't be released for pixelbook for a few days but may be available
>    on your chromebox).
>    - If the newer 72 version doesn't fix this for you can you try going
>    to chrome://flags#network-service and toggling it off? Does it work with
>    the network service off? Does it work if you set network service to on?
>    (you need to restart Chrome OS after each change).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_googlearchive_chromeos-5Fsaml-5Fapps_issues_1-23issuecomment-2D466160128&d=DwMFaQ&c=vZI7FCk37fZpIpwDI9E_qA&r=G5i84GOr660oBm5C31AjaxgwGeNabEVSCxhqWzPl5ko&m=T8z2qI9NeBGPgSXGh35rZcvMtlimIS6wiPwMMugPjT8&s=n-R4zL2sRLY2O0Q5eoWT2ot9N0hqDl0SC4t6o3Ii-ZU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Acqq4wMCCmV5eOZJFbgii61iPu-5FyINaAks5vPwXlgaJpZM4bFtnT&d=DwMFaQ&c=vZI7FCk37fZpIpwDI9E_qA&r=G5i84GOr660oBm5C31AjaxgwGeNabEVSCxhqWzPl5ko&m=T8z2qI9NeBGPgSXGh35rZcvMtlimIS6wiPwMMugPjT8&s=wk2D9rZroJyT7CrUeK2DO429glvLdosW-1ITKOfm9Vs&e=>
> .
>

-- 

Notice to recipient: This e-mail is only meant for the intended recipient 
of the transmission, and may be a confidential communication or a 
communication privileged by law. If you received this e-mail in error, any 
review, use, dissemination, distribution, or copying of this e-mail is 
strictly prohibited. Please notify us immediately of the error by return 
e-mail and please delete this message from your system. Thank you in 
advance for your cooperation.

**Comment by nlochrie** [comment] 2019-03-06 23:04
I tried chrome://flags#network-service (enabled and disabled) and it didn't work.

We had about 5 test pixelbooks and noticed that after we upgraded from 71 (when it was working), and updating it to 72, it broke..

Also tried chrome://flags#network-service with 72.  Is broke.

Is there a log file for what saml for chrome is logging to?

**Comment by nlochrie** [comment] 2019-03-06 23:38
Here is the json file for saml for chrome
Looking for a log file if it has the capability, Thanks


    "whitelist" : {
        "Value" : [
            {
            "appId" : "haiffjcadagjlijoggckpgfnoeiflnem",
            "domain" : "pingidentity.com"
            }
        ]
     }
}

**Comment by nlochrie** [comment] 2019-03-07 00:19
We are using Ping for the chromeos (pixelbok and chromebox).
Do you think we need to define more?   What does "Secure" do?
What's interesting is that it all worked great with version "71".. and stopped after we upgraded to "72"

properties": {
          "appId": { 
              "title": "Whitelisted App ID",
              "description": "ID of the app that the admin wishes to grant a subset of the user's cookies to.",
              "type": "string"
          },
          "domain": { 
            "title": "Domain for granted cookies",
            "description": "A domain for which the helper extension will extract cookies from the user's profile and hand over to requesting appId. This can be further refined by the admin with criteria for cookie name, secure attribute, and path.",
            "type": "string"
          },
          "name": {
            "title": "Name for granted cookies",
            "description": "A name for which the helper extension will filter the cookies from the user's profile and hand over to requesting appId.",
            "type": "string"
          },
          "path": {
            "title": "Path for granted cookies",
            "description": "A path for which the helper extension will filter the cookies from the user's profile and hand over to requesting appId.",
            "type": "string"
          },
          "secure": {
            "title": "Secure property for granted cookies",
            "description": "The secure property for which the helper extension will filter the cookies from the user's profile and hand over to requesting appId.",
            "type": "boolean"

**Comment by nlochrie** [comment] 2019-03-13 15:40
73 came out and we tested it.  Still broken.  Works with 71 all day long.. just not 72, and 73.

Can your verify that this extension works with 72, 73?

**Comment by zakhackpacklack** [comment] 2019-04-10 23:05
HA SUCKER

**Comment by yowkah** [comment] 2019-04-25 09:56
Just wanted to confirm that im noticing the same issue here using enrolled "Acer R13" and Acer "Spin 15" running ChromeOS 73.0.3683.114.

We intended to use this app for forwarding a SAML cookie to the Citrix Workspace App. But so far i can't get it to work properly. 

---- edit ----

Checked the addon using the inspector. When using the debugger it looks like this extension still works properly. When i open the citrix workspace app, it will send a message asking for all the cookies and supplies a callback function. The callback function gets called succesfully and the correct cookies are supplied as arguments for the callback. I will take this issue towards Citrix instead.

**Comment by nlochrie** [comment] 2019-04-25 16:31
I feel better now that someone else has also observed this.

We are a Google Gsuite / Chrome Pro shop and we are trying to replace our Win7 Wyse terminals with Google Boxes.  

With Version 72 before it broke, it was working great on Chromebox's and Chromebooks successfully using the SAML SS for chrome Apps with Citrix Workspace using Citrix FAS (Federated Auth Service).

It was awesome for a end user to authenticate using a 2nd factor on the chromebox/pixelbook, and having the saml authenticate all the way to opening up citrix workspace seemlessly already authenticated showing all the published apps.

But, It's still broken even with the latest updates.

Do you think we can escalate this up the Support Layers at Google?    We will be talking to our Google rep about this also to see if it can be escalated.

**Comment by yowkah** [comment] 2019-04-26 09:49
@nlochrie i have been using the developpertools from chrome on both the "SAML SSO for chrome apps" and the citrix receiver. 

From what i can see, the "SAML SSO for Chrome apps" sends forward the correct cookies, however for some reason, whenever i inspect the web-view in the "citrix workspace"  app. Im just missing one of the cookies used for SAML. Which is the one containing what appears to be a JWT token.

The code for the "citrix  workspace app" is  unfortunately obfuscated to some degree, making debugging it properly a tad difficult. But from what i can see it just leaves out of one of the 3 cookies sent by the "SAML SSO for chrome apps" extension. 

I think we shouldn't be looking at google for this, but instead should be looking at Citrix for what changed in their workspace app, unfortunately i dont know a way to set my chromebook back to version 71 to be able to  see what the whole dance is supposed to look like. Do you have a way of doing that?

PS im in a pretty small company ( less than 300 chromebooks, less than 1500 employees)  so we dont have a lot of suction with either Google or Citrix in this regard.

**Comment by yowkah** [comment] 2019-04-26 11:31
@nlochrie looks like i found the cause.

The issue lies here:
![image](https://user-images.githubusercontent.com/6965826/56804794-3b55c200-6827-11e9-8cb9-e4881060e09d.png)

The Citrix Workspace app actually tries to set the cookie on the event specified. Since chrome 72 this is no longer possible and thus it no longer works. When I inspect the Citrix Workspace App i can see it happening in the debugger as well... the cookies are extracted using the "getAllCookies" message provided by this extension. and then are set in the "onHeadersReceived" event on the webview's request property. This doesn't work since chrome 72. I will try contacting Citrix about this.

**Comment by nlochrie** [comment] 2019-05-08 16:27
Awesome!  Great Job.

If you haven't already, mention there are other Citrix customers that are trying to use Chromebooks as endpoints with Workspace Client.  We have 500+ winterminals that are slated to be replaced.

Thanks

**Comment by yowkah** [comment] 2019-05-15 14:09
@nlochrie 
Citrix support came through. you can check the following article:
https://support.citrix.com/article/CTX253863

They have a fix in a private release. This worked for us, it will probably hit production on the next update of citrix workspace app.

i think you can close this issue. you might be able to contact citrix support citing this article, asking if you can have access to the private release to test the fix for yourself.

**Closed as completed** 2022-11-11 20:00 UTC
